name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirments.txt
      - name: Run tests
        run: pytest -v
  docker:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
     - 
       name: Login to Docker Hub
       uses: docker/login-action@v3
       with:
          username: afzalkunnath
          password: Afzal@#$890
     -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: user/app:latest
    
